### ISSUE TITLE
Could not install under node 0.12 + ubuntu

### ISSUE THREAD

**Issue by hurricaneLTG** [tomgco/cpu-profiler#4]
Has anyone else tried this yet? Let me know and I can provide any other info required like install logs
Thanks

**Comment by leedm777** [comment]
It installs successfully, but fails to load.

This was in `builderror.log`:

```
../cpu_profiler.cc:15:13: error: ‘v8::ThrowException’ has not been declared
   using v8::ThrowException;
             ^
../cpu_profiler.cc: In static member function ‘static void nodex::CpuProfiler::GetProfilesCount(const v8::FunctionCallbackInfo<v8::Value>&)’:
../cpu_profiler.cc:33:58: error: ‘class v8::CpuProfiler’ has no member named ‘GetProfileCount’
     args.GetReturnValue().Set(isolate->GetCpuProfiler()->GetProfileCount());
                                                          ^
../cpu_profiler.cc: In static member function ‘static void nodex::CpuProfiler::GetProfile(const v8::FunctionCallbackInfo<v8::Value>&)’:
../cpu_profiler.cc:40:39: error: ‘New’ is not a member of ‘v8::String’
       ThrowException(Exception::Error(String::New("No index specified")));
                                       ^
../cpu_profiler.cc:40:73: error: ‘ThrowException’ was not declared in this scope
       ThrowException(Exception::Error(String::New("No index specified")));
                                                                         ^
../cpu_profiler.cc:43:43: error: ‘New’ is not a member of ‘v8::String’
       ThrowException(Exception::TypeError(String::New("Argument must be an integer")));
                                           ^
../cpu_profiler.cc:43:86: error: ‘ThrowException’ was not declared in this scope
       ThrowException(Exception::TypeError(String::New("Argument must be an integer")));
                                                                                      ^
../cpu_profiler.cc:47:60: error: ‘class v8::CpuProfiler’ has no member named ‘GetCpuProfile’
     const CpuProfile* profile = isolate->GetCpuProfiler()->GetCpuProfile(index);
                                                            ^
../cpu_profiler.cc: In static member function ‘static void nodex::CpuProfiler::DeleteAllProfiles(const v8::FunctionCallbackInfo<v8::Value>&)’:
../cpu_profiler.cc:74:32: error: ‘class v8::CpuProfiler’ has no member named ‘DeleteAllCpuProfiles’
     isolate->GetCpuProfiler()->DeleteAllCpuProfiles();
                                ^
make: *** [Release/obj.target/profiler/cpu_profiler.o] Error 1
```

**Comment by hhamilto** [comment]
Have you found any profiling tools that work in node 0.12? I last looked a month or two ago and couldn't find any that seemed stable. If I remember, the only one that worked read in a v8.log that was generated by passing the --prof option to node, but it had a buggy gui.

**Comment by tomgco** [comment]
Yeah, incompatibilities with 0.12 is a pain. @hhamilto https://github.com/thlorenz/v8-perf might be a good resource to get started.
